services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile_dev.dockerfile
    stdin_open: true
    tty: true
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - ENVIRONMENT=development
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    command: ['uvicorn', 'main:app', '--host', '0.0.0.0', '--port', '${BACKEND_PORT}', '--reload']
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
